<?php

define('OPEN_JOURNAL_PREFIX_PATH', 'journal');
define('OPEN_JOURNAL_SUB_LANG', 'Thai');
define('OPEN_JOURNAL_SUB_LANG_CODE', 'th');
define('OPEN_JOURNAL_ABSTRACT_MAX_LENGTH', 500);
define('OPEN_JOURNAL_ALLOWED_FILE_TYPE', 'doc  docx');

function open_journal_menu() {
  $items[OPEN_JOURNAL_PREFIX_PATH]	= array(
    'title' => 'Open Journal',
    'page callback' => 'open_journal_overview',
    'access arguments' => array('access open journal'),
    'type' => MENU_CALLBACK,
  );

  $items[OPEN_JOURNAL_PREFIX_PATH.'/login'] = array(
    'title' => 'Login',
    'page callback' => 'open_journal_login',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/open_journal_login_form.inc',
  );

  $items[OPEN_JOURNAL_PREFIX_PATH.'/register'] = array(
    'title' => 'Register',
    'page callback' => 'open_journal_register',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/open_journal_register_form.inc',
  );  
  $items[OPEN_JOURNAL_PREFIX_PATH.'/account/setting'] = array(
    'title' => 'Setting my account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('open_journal_account_setting_form'),
    'access arguments' => array('access open journal'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/open_journal_account_setting_form.inc',
  );

  $items[OPEN_JOURNAL_PREFIX_PATH.'/add'] = array(
    'title' => 'Add new journal',
    'page callback' => 'open_journal_information',
    'access arguments' => array('access open journal'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/open_journal_information_form.inc',
  ); 
  return $items;
}

function open_journal_theme() {

  return array(
    'open_journal_login' => array(
      'variables' => array(
        'form' => NULL,
        'condition' => NULL,
      ),
      'template' => 'templates/open-journal-login',
    ),

    'open_journal_register' => array(
      'variables' => array(
        'form' => NULL,
        'condition' => NULL,
      ),
      'template' => 'templates/open-journal-register',
    ),

    'open_journal_detail' => array(
      'variables' => array(
        'jid' => NULL,
        'content' => NULL,
      ),
      'template' => 'templates/open-journal-detail',
    ),

  );
}

function open_journal_permission() {
  return array(
    'access open journal' => array(
      'title' => t('Access open journal'),
      'description' => t('Perform user can lonin to join open journal.'),
    ),
  );
}

function open_journal_preprocess_html(&$vars) {
  if (user_is_logged_in()) {
    $vars['header_class'] = 'header-logged-in';
  }
  else {
    $vars['header_class'] = 'header-logged-out';
  }
}

function open_journal_preprocess_page(&$vars) {

  $mpath = drupal_get_path('module', 'open_journal');

  if(in_array($_GET['q'], array(OPEN_JOURNAL_PREFIX_PATH.'/login', OPEN_JOURNAL_PREFIX_PATH.'/register'))) {
    // TODO: change to settings upload file
    $vars['open_journal_logo1'] = FALSE;
    $vars['open_journal_logo2'] = theme('image', array(
      'path' => $mpath.'/images/default_logo2.png',
      'alt' => variable_get('site_name', ''),
    ));
    $vars['disabled_title'] = TRUE;
    $vars['page_class'] = 'page-sign';
  }
  else {

    $vars['open_journal_logo1'] = theme('image', array(
      'path' => $mpath.'/images/default_logo1.png',
      'alt' => variable_get('site_name', ''),
    ));
    $vars['open_journal_logo2'] = FALSE;
    $vars['disabled_title'] = FALSE;
    $vars['page_class'] = 'page-normal';
  }
  
}

function open_journal_overview() {

  return '# Journal list'.l('add', OPEN_JOURNAL_PREFIX_PATH.'/add');

}

function open_journal_login() {
  drupal_add_js(drupal_get_path('module','open_journal').'/js/open_journal_compact.js');
  return theme('open_journal_login', array(
    'form' => drupal_render(drupal_get_form('open_journal_login_form')),
    'condition' => 'CONDITION',
  ));
}

function open_journal_register() {
  drupal_add_js(drupal_get_path('module','open_journal').'/js/open_journal_compact.js');
  return theme('open_journal_register', array(
    'form' => drupal_render(drupal_get_form('open_journal_register_form')),
    'condition' => 'CONDITION',
  ));
}

function open_journal_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (!isset($_GET['destination'])) {
    drupal_goto(OPEN_JOURNAL_PREFIX_PATH.'/account/setting');
  }
}

function open_journal_form_user_admin_settings_alter(&$form, &$form_state) {
  // reorder fieldset weights
  $form['anonymous_settings']['#weight'] = -4;
  $form['admin_role']['#weight'] = -3;
  $form['registration_cancellation']['#weight'] = -2;
  $form['nocurrent_pass_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Require Current Password'),
    '#weight' => -1,
  );
  $form['nocurrent_pass_settings']['nocurrent_pass_disabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Do not require current password'),
    '#description' => t('Check this box to disable the "current password" field on the User Edit form.'),
    '#default_value' => variable_get('nocurrent_pass_disabled', TRUE),
  );
}

function open_journal_information() {

  $output =  theme('open_journal_detail', array(
    'content' => drupal_render(drupal_get_form('open_journal_information_form')),
  ));

  return $output;
}
